export const componentMapData = [
  { source: 'titlebar', component: 'TitleBar' },
  { source: 'activitybar', component: 'ActivityBar' },
  { source: 'panel-explorer', component: 'ExplorerPanel' },
  { source: 'panel-search', component: 'SearchPanel' },
  { source: 'panel-review', component: 'ReviewPanel' },
  { source: 'panel-dataset', component: 'DatasetPanel' },
  { source: 'panel-settings', component: 'SettingsPanel' },
  { source: 'view-welcome', component: 'WelcomeView' },
  { source: 'view-upload', component: 'UploadView' },
  { source: 'view-editor', component: 'EditorView' },
  { source: 'panel-mode-wysiwyg', component: 'EditorWysiwygMode' },
  { source: 'panel-mode-markdown', component: 'EditorMarkdownMode' },
  { source: 'panel-mode-html', component: 'EditorHtmlMode' },
  { source: 'panel-mode-preview', component: 'EditorPreviewMode' },
  { source: 'view-review', component: 'ReviewView' },
  { source: 'view-dataset', component: 'DatasetView' },
  { source: 'view-settings', component: 'SettingsView' },
  { source: 'statusbar', component: 'StatusBar' },
  { source: 'modal-overlay', component: 'ModalOverlay' },
  { source: 'toast', component: 'ToastLayer' },
];
